steps:
- id: package and upload chart
  name: gcr.io/$PROJECT_ID/cloudbuild-python:3.7-slim
  env:
    # helm uses HOME for state and requires plugins to be installed there.
    # HOME is set to /root during build, but cloud build it to /builder/home
    # and mounts an empty volume there, so we must set it back otherwise
    # helm can't see its plugins
    - HOME=/root
  entrypoint: bash
  args:
    - -c 
    - |
      helm package charts/gsm-controller
      helm repo add pace-charts gs://pace-chart-repo
      helm gcs push gsm-controller*.tgz pace-charts --public